name: Build mtkclient Windows EXE
on: { workflow_dispatch: {} }

jobs:
  build-mtk:
    runs-on: windows-latest
    steps:
      - name: Checkout mtkclient
        uses: actions/checkout@v4
        with:
          repository: bkerler/mtkclient

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # Bundle *all* mtkclient binaries + usb backends (WinFsp + libusb)
      - name: Build mtk.exe (fully bundled)
        shell: pwsh
        run: |
          pyinstaller --onefile --console mtk.py --name mtk `
            --collect-binaries mtkclient `
            --collect-submodules mtkclient `
            --hidden-import=fuse `
            --add-binary "mtkclient/Library/Filesystem/bin/winfsp-x64.dll;mtkclient/Library/Filesystem/bin" `
            --add-binary "mtkclient/Library/Filesystem/bin/winfsp-x86.dll;mtkclient/Library/Filesystem/bin" `
            --add-binary "mtkclient/Library/Connection/bin/libusb-1.0.dll;mtkclient/Library/Connection/bin"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mtk_win
          path: dist/mtk.exe
