name: Build mtkclient Windows EXE
on: { workflow_dispatch: {} }

jobs:
  build-mtk:
    runs-on: windows-latest
    steps:
      - name: Checkout mtkclient
        uses: actions/checkout@v4
        with:
          repository: bkerler/mtkclient

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # 🧩 Bundle WinFsp DLLs into the exe
      - name: Build mtk.exe (with WinFsp)
        shell: pwsh
        run: |
          $bin = "mtkclient/Library/Filesystem/bin"
          pyinstaller --onefile --console mtk.py --name mtk `
            --add-binary "$bin/winfsp-x64.dll;$bin" `
            --add-binary "$bin/winfsp-x86.dll;$bin"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mtk_win
          path: dist/mtk.exe
