name: Build PhoenixR1 Flasher (Windows)

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/windows-build.yml'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pyinstaller-hooks-contrib

      # NOTE: one-line command (PowerShell safe). No ^ characters.
      - name: Build with PyInstaller
        run: pyinstaller --onefile --noconsole --name PhoenixR1_Flasher --icon assets\phoenix.ico --collect-all PySide6 --add-data "assets\phoenix.ico;assets" --add-data "assets\phoenix.png;assets" gui_app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhoenixR1_Flasher_win
          path: dist/PhoenixR1_Flasher/**
